### ISSUE TITLE
Substituição de $

### ISSUE THREAD

**Issue by vanderalves** [ziul123/LI2Tipada#1]
Por motivo de simplicidade e uniformidade de notação, for favor, substitua todas ocorrências de  $

Obrigado

**Comment by ziul123** [comment]
Substitui todas as ocorrências em Interpreter.hs, para não conflitar com o estilo do resto do arquivo. Porém, a substituição na arquivo TestInterpreter.hs seria muito demorada, e desnecessária, pois o arquivo só utiliza esse estilo.
