### ISSUE TITLE
45 - 50 elminiação de redundância

### ISSUE THREAD

**Issue by vanderalves** [ziul123/LI2Tipada#2]
@ziul123:  Nas linhas 46-50, favor eleminar a redundância em repetidas chamadas a eval, utilizando where (pode usar o where que já tem lá colocando novas linhas) com pattern matching 

Exemplo (fazer o mesmo com pares):

 Ident "head" -> head . l $ eval environment $ head lexp
 Ident "tail" -> ValorList $ tail . l $ eval environment $ head lexp
================> 
Ident "head" -> h 
Ident "tail"  -> ValorList t 
where
 (h,t) =  l (eval environment (head lexp))
...

**Comment by ziul123** [comment]
Resolvido, porém tive que mudar a indentação do where para pegar a case expression inteira, e o padrão (h:t) para lista não funciona porque não é exaustivo.
